version: '3'
services:
  server:
    image: redash/redash:latest
    env_file: /data0/redash_data/env
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_MAIL_SERVER: "127.0.0.1"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: "Q422k6vaXUk8"
      REDASH_WEB_WORKERS: 4
    restart: always

  worker:
    image: redash/redash:latest
    env_file: /data0/redash_data/env
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_COOKIE_SECRET: "Q422k6vaXUk8"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: always
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    env_file: /data0/redash_data/env
    image: postgres:9.5.6-alpine
    volumes:
      - /data0/redash_data/postgres-data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: redash/nginx:latest
    ports:
      - "8070:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
