#!/bin/bash
# 此脚本主要用于练习比getopt更高级的命令 getopts
# 环境变量 OPTARG 用于记录当前选项的参数
# 环境变量 OPTIND 用于记录当前命令行参数对应的位置
# 局部变量 opt 用于记录当前选项的对应值
while getopts ab:c opt; do
    case "$opt" in
    a) echo "Found the #$OPTIND -a option" ;;
    b) echo "Found the #$OPTIND -b option, with value $OPTARG" ;;
    c) echo "Found the #$OPTIND -c option" ;;
    *) echo "Unknown #$OPTIND option: $opt" ;;
    esac
done
