_id String
create_time String
update_time String
nick String
is_create_qc_engine_shop String
is_close String
groups String
nlu_code String
shop_id String
is_start_use String
start_use_time DateTime64(3)
expire_time DateTime64(3)
version UInt32
whitelist Array(String)
is_phone_verified String
phone String
name String
source String