CREATE TABLE app_growth.customer_renewal_details_local ON CLUSTER cluster_3s_2r (
    `customer_name` String,
    `customer_id` String,
    `tonnage_level` String,
    `order_id` String,
    `order_no` String,
    `record_type` String,
    `amount` Float32,
    `annual_value` Float32,
    `annualized_amount` Float32,
    `contract_start_date` String,
    `real_contract_end_date` String,
    `service_end_date` String,
    `renew_order_id` String,
    `renew_order_no` String,
    `renew_amount` Float32,
    `renew_annual_value` Float32,
    `renew_annualized_amount` Float32,
    `renew_contract_start_date` String,
    `renew_real_contract_end_date` String,
    `renew_service_end_date` String,
    `is_complete` String,
    `yc_amount` Float32,
    `cus_day` String,
    `maintainer` String,
    `owner` String,
    `maintainer_id` String,
    `owner_id` String,
    `beisen_day` String,
    `owner_first` String,
    `owner_second` String,
    `owner_third` String,
    `owner_fourth` String,
    `maintainer_first` String,
    `maintainer_second` String,
    `maintainer_third` String,
    `maintainer_fourth` String,
    `service_level_day` String,
    `saas_annualized_value` Float64,
    `customized_annualized_value` Float64,
    `bpo_monthly_value` Float64,
    `saas_vip_level` String,
    `bpo_vip_level` String
) ENGINE = ReplicatedMergeTree(
    '/clickhouse/{database}/tables/{layer}_{shard}/{table}',
    '{replica}'
) PARTITION BY day
ORDER BY (order_id, customer_id) SETTINGS index_granularity = 8192,
    storage_policy = 'rr'