recv_cnick_cnt, 咨询买家数
reply_cnick_cnt, 回复买家数
m_reply_cnick_cnt, 人工回复买家数
session_cnt, 会话数
first_reply_within_thirty_secs_session_cnt, 
m_first_reply_within_thirty_secs_session_cnt
recv_msg_cnt
send_msg_cnt
m_send_msg_cnt
qa_sum
m_qa_sum
reply_interval_secs_sum
m_reply_interval_secs_sum
reply_interval_secs_avg
m_reply_interval_secs_avg
first_reply_within_thirty_secs_session_rat
m_first_reply_within_thirty_secs_session_rat
send_msg_rat
m_send_msg_rat
reply_cnick_rat
m_reply_cnick_rat