客服询单人数, {{cycle}}_ask_order_uv
在线销售额, {{cycle}}_ask_order_paid_amt
已售产品台数-出库, {{cycle}}_out_of_stock_goods_sale_count
已售产品台数-销售, {{cycle}}_paid_goods_sale_count
客服销售人数-下单人数, {{cycle}}_ask_order_created_uv
客服销售订单数-下单量, {{cycle}}_ask_order_created_cnt
出库人数（不含静默）, {{cycle}}_out_of_stock_uv
在线销售额（不含静默）, {{cycle}}_ask_order_paid_amt
出库金额-出库销售额， {{cycle}}_out_of_stock_amt
出库量， {{cycle}}_out_of_stock_cnt