CREATE TABLE dipper_ods.shop_overview_day (
    shop_id STRING NOT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION,
    platform STRING NOT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION,
    day INT NOT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION,
    sm_recv_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    sm_recv_uv BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    sm_idfy_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    sm_trans_uv BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    sm_repl_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    hm_recv_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    hm_recv_uv BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    hm_idfy_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    hm_repl_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    kb_send_num BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    kb_paid_buyer_num BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    kb_paid_order_num BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    kb_paid_order_payment BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    recv_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    recv_uv BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    idfy_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    repl_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    use_account_cnt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    order_pemt_amt BIGINT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    rs_human_avg_resp_interval FLOAT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    rs_hci_avg_resp_interval FLOAT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    rs_reduce_interval FLOAT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    rs_human_work_ratio FLOAT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    rs_human_save_hours FLOAT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION DEFAULT 0,
    order_created_pemt_amt FLOAT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION,
    non_silent_reminder_pemt_amt FLOAT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION,
    ro_repl_cnt_filter INT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION,
    total_repl_cnt_filter INT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION,
    PRIMARY KEY (shop_id, platform, day)
)
PARTITION BY RANGE (day)
(
    PARTITION 20221130<=VALUES<20221131
)
STORED AS KUDU TBLPROPERTIES ('kudu.master_addresses' = 'cdh0,cdh1,cdh2')