[
  {
    "id": "652220a80eddf6000188f851",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696735398,
    "ms_timestamp": 1696735398993,
    "source": 1,
    "content": "/:072",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [
      14
    ],
    "abnormal_score": [
      {
        "type": 14,
        "name": "单表情回复",
        "count": 0,
        "score": 0
      }
    ],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": false,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "222"
            ],
            "hitter": "222;",
            "operator": "word/none",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696735400
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "652220bae8d7ccce155a7f40",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696735417,
    "ms_timestamp": 1696735417984,
    "source": 0,
    "content": "你好",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "c0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": false,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 3,
    "question": "开始语（你好等）",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "641d1116539a8b30e3a3beee",
        "count": 1,
        "score": 0,
        "name": "测试你好发送",
        "check_step": 0,
        "raw_data": "{\"id\":\"641d1116539a8b30e3a3beee\",\"create_time\":\"2023-03-24T02:55:18.848Z\",\"update_time\":\"2023-03-24T02:55:37.681Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"62e1255263761536e2ed7e3e\",\"template_id\":\"641d110e539a8b30e3a3beea\",\"name\":\"测试你好发送\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"\",\"name\":\"测试你好发送\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger_once\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"and\",\"sub_conds\":[{\"keywords\":[\"你好\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"你好\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":0},\"seek_type\":\"content.is_txt.msg@buyer\"}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":3,\"notify_way\":1,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "你好"
            ],
            "hitter": "你好;",
            "operator": "word/one",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696735418
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "652220bb4bb2ea000159a34d",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696735419,
    "ms_timestamp": 1696735419354,
    "source": 1,
    "content": "online 线上环境标记------------------- 重复答案​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "222"
            ],
            "hitter": "222;",
            "operator": "word/none",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696735419
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "652220c24fa7560001389791",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696735425,
    "ms_timestamp": 1696735425209,
    "source": 1,
    "content": "online 线上环境标记------------------- 重复答案​​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "222"
            ],
            "hitter": "222;",
            "operator": "word/none",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696735426
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "1.0.0",
    "msg_scenes_source": "7.1.0"
  },
  {
    "id": "652220cc2371efa01b94cc76",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696735436,
    "ms_timestamp": 1696735436250,
    "source": 0,
    "content": "<a href=\"https://detail.tmall.com/item.htm?id=681094269342&ut_sk=1.Yowvll6ucS0DAPQwose2TbWa.21380790.Contacts.cc_chat_share\" target=\"_blank\">https://detail.tmall.com/item.htm?id=681094269342&ut_sk=1.Yowvll6ucS0DAPQwose2TbWa.21380790.Contacts.cc_chat_share</a>",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "c0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": false,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": -6,
    "question": "收到买家发的商品链接",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "652220cd7eb2c60001d65387",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696735437,
    "ms_timestamp": 1696735437640,
    "source": 1,
    "content": "online 线上环境标记------------------- 111111111111111111111111111111111111111​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "111"
            ],
            "hitter": "111;",
            "operator": "word/one",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696735437
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "652220d47be6420001751aa8",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696735443,
    "ms_timestamp": 1696735443255,
    "source": 1,
    "content": "online 线上环境标记------------------- 111111111111111111111111111111111111111​​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "111"
            ],
            "hitter": "111;",
            "operator": "word/one",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696735623
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "1.0.0",
    "msg_scenes_source": "7.1.0"
  },
  {
    "id": "65222306340ab4dae6cb4e58",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736005,
    "ms_timestamp": 1696736005634,
    "source": 0,
    "content": "没看见",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "c0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": false,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 200339858,
    "question": "没看见/没找到",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "65222306dcfda700010ba91d",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736006,
    "ms_timestamp": 1696736006880,
    "source": 1,
    "content": "online 线上环境标记------------------- 亲，您可将您的问题留言额，掌柜回来后会及时回复您的​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "222"
            ],
            "hitter": "222;",
            "operator": "word/none",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696736006
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "6522230d39c09d00012d34b4",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736012,
    "ms_timestamp": 1696736012454,
    "source": 1,
    "content": "online 线上环境标记------------------- 亲，您可将您的问题留言额，掌柜回来后会及时回复您的​​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "222"
            ],
            "hitter": "222;",
            "operator": "word/none",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696736013
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "1.0.0",
    "msg_scenes_source": "7.1.0"
  },
  {
    "id": "6522235745e9fbf7b5f95392",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736087,
    "ms_timestamp": 1696736087351,
    "source": 0,
    "content": "太薄了",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "c6",
    "emotion_name": "对产品不满",
    "algo_emotion": 6,
    "emotion_score": 5,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": false,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 12927,
    "question": "表示商品太薄/厚",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "65222381b810ba55e1ea4447",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736128,
    "ms_timestamp": 1696736128918,
    "source": 0,
    "content": "试过了",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "c0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": false,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 200336032,
    "question": "试过了",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "652223958554c13f6e7cf529",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736149,
    "ms_timestamp": 1696736149271,
    "source": 0,
    "content": "试过了",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "c0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": false,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 200336032,
    "question": "试过了",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "652223961227bf00017091c6",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736150,
    "ms_timestamp": 1696736150573,
    "source": 1,
    "content": "online 线上环境标记------------------- 好的哦​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "222"
            ],
            "hitter": "222;",
            "operator": "word/none",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696736150
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "",
    "msg_scenes_source": ""
  },
  {
    "id": "6522239d7be642000175d48c",
    "dialog_id": "652220a84e04f90001ae7b2a",
    "timestamp": 1696736156,
    "ms_timestamp": 1696736156096,
    "source": 1,
    "content": "online 线上环境标记------------------- 好的哦​​​",
    "content_type": "",
    "qc_word_stat": [],
    "emotion": "s0",
    "emotion_name": "中性",
    "algo_emotion": 0,
    "emotion_score": 0,
    "suspected_emotion": false,
    "abnormals": [],
    "abnormal_score": [],
    "suspected_abnormals": [],
    "excellents": [],
    "excellent_score": [],
    "auto_send": true,
    "is_transfer": false,
    "qc_event_type": "",
    "cnick": "tb31771069",
    "open_uid": "AAHkZosOAKdpZ1hrVDhoZJwD",
    "qid": 0,
    "question": "",
    "snick": "木月瑞希尔:gg",
    "room_nick": "",
    "is_remind_message": false,
    "rule_stats": [],
    "rule_add_stats": [],
    "xrule_stats": [
      {
        "id": "63903416d7f98b06548d9e00",
        "count": 1,
        "score": 0,
        "name": "转接消息打标",
        "check_step": 0,
        "raw_data": "{\"id\":\"63903416d7f98b06548d9e00\",\"create_time\":\"2022-12-07T06:35:02.499Z\",\"update_time\":\"2023-04-03T09:21:51.512Z\",\"company_id\":\"5f73e9c1684bf70001413636\",\"platform\":\"tb\",\"qc_norm_id\":\"62e1255263761536e2ed7daf\",\"qc_norm_group_id\":\"632c0c277eecaf4ff58f8fc4\",\"template_id\":\"63903414d7f98b06548d9dfe\",\"name\":\"转接消息打标\",\"seller_nick\":\"\",\"rule_category\":3,\"rule_type\":0,\"settings\":{\"cal_op\":1,\"check_sale_status\":[],\"check_step\":-1,\"description\":\"111\",\"name\":\"转接消息打标\",\"score\":1,\"version\":true,\"xact\":{\"tag_mode\":\"trigger\"},\"xrule\":{\"f_hit_min\":0,\"filter\":{},\"trigger\":{\"logic_op\":\"and\",\"sub_conds\":[{\"logic_op\":\"or\",\"sub_conds\":[{\"qa_flags\":\"transfer_end\",\"seek_conf\":{\"qa_flags\":\"transfer_end\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"qa_flags\":\"transfer_begin\",\"seek_conf\":{\"qa_flags\":\"transfer_begin\"},\"seek_type\":\"flag.qa_flags.msg\"},{\"keywords\":[\"111\"],\"op\":\"one\",\"seek_conf\":{\"keywords\":[\"111\"],\"op\":\"one\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"222\"],\"op\":\"none\",\"seek_conf\":{\"keywords\":[\"222\"],\"op\":\"none\",\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100},{\"keywords\":[\"3333\"],\"op\":\"all\",\"seek_conf\":{\"keywords\":[\"3333\"],\"op\":\"all\",\"options\":{\"threshold\":100},\"source\":1},\"seek_type\":\"content.is_txt.msg@seller\",\"source\":1,\"threshold\":100}]}]}}},\"check\":true,\"check_target\":1,\"alert_level\":2,\"notify_way\":2,\"notify_target\":1,\"score\":0,\"threshold\":0,\"special_settings\":null,\"Status\":1}",
        "details": [
          {
            "on": "trigger",
            "uni": "content.is_txt.msg",
            "options": [
              "222"
            ],
            "hitter": "222;",
            "operator": "word/none",
            "numeration": 1
          },
          {
            "on": "filter",
            "uni": "ok.filter.empty",
            "options": [],
            "hitter": "empty filter;",
            "operator": "",
            "numeration": 1
          }
        ],
        "hit_ts": 1696736336
      }
    ],
    "wx_rule_stats": [],
    "wx_rule_add_stats": [],
    "withdraw_ms_time": 0,
    "tags": [],
    "mark": "",
    "wipe_abnormals": [],
    "wipe_excellents": [],
    "wipe_rule_stats": [],
    "wipe_emotion": null,
    "apels": [],
    "msg_content_type": "1.0.0",
    "msg_scenes_source": "7.1.0"
  }
]