create table public.snick_stat (
    day integer not null,
    company_id text not null,
    shop_id text not null,
    platform text not null,
    seller_nick text not null,
    snick text not null,
    employee_id text not null,
    employee_name text not null,
    department_id text not null,
    department_name text not null,
    qc_norm_id text not null,
    qc_norm_name text not null,
    qc_norm_tag_cnt integer not null,
    qc_norm_ai_tag_cnt integer not null,
    qc_norm_custom_tag_cnt integer not null,
    qc_norm_manual_tag_cnt integer not null,
    qc_norm_alert_tag_cnt integer not null,
    dialog_tag_cnt integer not null,
    dialog_ai_tag_cnt integer not null,
    dialog_custom_tag_cnt integer not null,
    dialog_manual_tag_cnt integer not null,
    subtract_score_sum integer not null,
    add_score_sum integer not null,
    ai_subtract_score_sum integer not null,
    ai_add_score_sum integer not null,
    custom_subtract_score_sum integer not null,
    custom_add_score_sum integer not null,
    manual_subtract_score_sum integer not null,
    manual_add_score_sum integer not null,
    dialog_score_avg double precision not null,
    dialog_cnt integer not null,
    excellent_dialog_cnt integer not null,
    tagged_dialog_cnt integer not null,
    ai_tagged_dialog_cnt integer not null,
    custom_tagged_dialog_cnt integer not null,
    manual_tagged_dialog_cnt integer not null,
    subtract_score_dialog_cnt integer not null,
    add_score_dialog_cnt integer not null,
    manual_marked_dialog_cnt integer not null,
    ai_subtract_score_dialog_cnt integer not null,
    ai_add_score_dialog_cnt integer not null,
    ai_zero_score_tagged_dialog_cnt integer not null,
    custom_subtract_score_dialog_cnt integer not null,
    custom_add_score_dialog_cnt integer not null,
    custom_zero_score_tagged_dialog_cnt integer not null,
    manual_subtract_score_dialog_cnt integer not null,
    manual_add_score_dialog_cnt integer not null,
    manual_zero_score_tagged_dialog_cnt integer not null,
    constraint idx_snick_stat_day_company_id_shop_id_snick 
        unique (day, company_id, shop_id, snick)
);

comment on table public.snick_stat is '子账号粒度-每日质检结果统计表';

alter table public.snick_stat
    owner to xqc;