#!/bin/bash
# 此脚本主要用于练习getopt命令,使用getopt命令格式化脚本的输入选项和参数
# 并使用set -- 命令来替换当前脚本的命令行参数为格式化后的命令行参数
set -- $(getopt ab:cd "$@")
while [ "$1" != "" ]; do
    case "$1" in
    "-a")
        echo "Found the -a option"
        ;;
    "-b")
        param=$2
        echo "Found the -b option with parameter value $param"
        ;;
    "-c")
        echo "Found the -c option"
        ;;
    "--")
        shift
        break
        ;;
    *)
        echo "$1 is not a option"
        ;;
    esac
    shift
done

count=1
for param in "$@"; do
    echo "Parameter #$count:$param"
    count = $(($count + 1))
done
