apiVersion: v1
data:
  config.json: |2-

    {
        "http_endpoint": ":8155",
        "grpc_endpoint": ":8156",
        "stream_step_size": 1000,
        "std_log": {
            "level": "debug",
            "file": "/var/log/xiaoduo/query-sdk.log",
            "err_file": "/var/log/xiaoduo/query-sdk.err.log",
            "app_name": "query-sdk",
            "auto_init": true
        },
        "api_log": {
            "level": "debug",
            "file": "/var/log/xiaoduo/query-sdk.api.log",
            "app_name": "query-sdk",
            "auto_init": true
        },
        "switcher": ["etcd001:2379"],
        "rate_limit": {
            "default": {
                "impala": {
                    "qps": 10,
                    "max": 10
                },
                "clickhouse": {
                    "qps": 20,
                    "max": 20
                }
            },
            "log": {
                "impala": {
                    "qps": 10,
                    "max": 10
                },
                "clickhouse": {
                    "qps": 20,
                    "max": 20
                }
            },
            "data-visual":{
                "impala": {
                    "qps": 10,
                    "max": 10
                },
                "clickhouse": {
                    "qps": 20,
                    "max": 40
                }
            },
            "qc-object":{
                "impala": {
                    "qps": 100,
                    "max": 50
                },
                "clickhouse": {
                    "qps": 100,
                    "max": 50
                }
            },
            "keban-group": {
                "impala": {
                    "qps": 3,
                    "max": 3
                },
                "clickhouse": {
                    "qps": 3,
                    "max": 3
                }
            },
            "x-data-tb": {
                "impala": {
                    "qps": 99999,
                    "max": 99999
                },
                "clickhouse": {
                    "qps": 99999,
                    "max": 99999
                }
            }
        },
        "storage": {
            "ping": "20s",
            "impala": {
                "default": ["10.22.134.218:21050","10.22.134.219:21050","10.22.134.220:21050"],
                "bee": ["10.22.134.218:21000","10.22.134.219:21000","10.22.134.220:21000"]
            },
            "clickhouse": {
                "log": ["tcp://10.22.131.153:9000?read_timeout=300&max_memory_usage=20000000000","tcp://10.22.131.154:9000?read_timeout=300&max_memory_usage=20000000000","tcp://10.22.131.217:9000?read_timeout=300&max_memory_usage=20000000000"],
                "default": ["tcp://10.22.134.218:19000?read_timeout=300&alt_hosts=10.22.134.219:19000,10.22.134.220:19000&max_memory_usage=20000000000","tcp://10.22.134.219:19000?read_timeout=300&alt_hosts=10.22.134.218:19000,10.22.134.220:19000&max_memory_usage=20000000000","tcp://10.22.134.220:19000?read_timeout=300&alt_hosts=10.22.134.218:19000,10.22.134.219:19000&max_memory_usage=20000000000"],
                "mp": ["tcp://10.22.134.218:19000?read_timeout=300&alt_hosts=10.22.134.219:19000,10.22.134.220:19000&max_memory_usage=20000000000","tcp://10.22.134.219:19000?read_timeout=300&alt_hosts=10.22.134.218:19000,10.22.134.220:19000&max_memory_usage=20000000000","tcp://10.22.134.220:19000?read_timeout=300&alt_hosts=10.22.134.218:19000,10.22.134.219:19000&max_memory_usage=20000000000"],
                "keban": ["tcp://10.22.133.209:19000?read_timeout=300&alt_hosts=10.22.133.210:19000,10.22.133.211:19000&max_memory_usage=20000000000","tcp://10.22.133.210:19000?read_timeout=300&alt_hosts=10.22.133.209:19000,10.22.133.211:19000&max_memory_usage=20000000000","tcp://10.22.133.211:19000?read_timeout=300&alt_hosts=10.22.133.209:19000,10.22.133.210:19000&max_memory_usage=20000000000"],
                "report": ["tcp://10.22.133.213:19000?read_timeout=300&alt_hosts=10.22.133.214:19000&max_memory_usage=20000000000","tcp://10.22.133.213:29000?read_timeout=300&alt_hosts=10.22.133.214:29000&max_memory_usage=20000000000"]
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    envctl.xiaoduoai.com/md5sum: 916dc3e265840248fa687b3bf037f1ef
  creationTimestamp: "2021-08-03T12:30:33Z"
  name: conf-query-sdk
  namespace: test-mini-cond
  resourceVersion: "12693658"
  selfLink: /api/v1/namespaces/test-mini-cond/configmaps/conf-query-sdk
  uid: db93b1c5-8740-462e-b67e-6f09e58d5c07
