apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/restartedAt: "2023-05-19T11:22:47+08:00"
      kubernetes.io/limit-ranger: 'LimitRanger plugin set: memory request for container
        network-debug-tools; memory limit for container network-debug-tools'
      pod-injected.k8s-webhooks.xiaoduoai.com: 2023-05-19 03:22:47.522412322 +0000
        UTC m=+2250277.188560605
    creationTimestamp: "2023-05-19T03:22:47Z"
    generateName: query-panel-deploy-6bd4479c48-
    labels:
      app: query-panel
      pod-template-hash: 6bd4479c48
    name: query-panel-deploy-6bd4479c48-5qpl4
    namespace: dev-lane
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: query-panel-deploy-6bd4479c48
      uid: 5f1a125d-ca93-4145-b78d-3162b15ec8c5
    resourceVersion: "64872767"
    selfLink: /api/v1/namespaces/dev-lane/pods/query-panel-deploy-6bd4479c48-5qpl4
    uid: c228e57e-11d1-4151-bf42-69726d0c83db
  spec:
    containers:
    - env:
      - name: XD_SVCNAME
        value: query-panel
      - name: XD_LOGDIR
        value: /var/log/xiaoduo/squirrel
      - name: XD_REAL_HOST
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      image: registry.cn-zhangjiakou.aliyuncs.com/xiaoduoai/bigdata-query-panel:feat-drill-display
      imagePullPolicy: Always
      name: query-panel
      ports:
      - containerPort: 8096
        name: http
        protocol: TCP
      - containerPort: 18096
        name: prof
        protocol: TCP
      - containerPort: 28096
        name: grpc
        protocol: TCP
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 100Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/config
        name: config-volume
      - mountPath: /var/log/xiaoduo
        name: log-volume
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-dxzcg
        readOnly: true
    - command:
      - /app/sys_monitor
      - -listen-address
      - :9091
      image: registry.cn-zhangjiakou.aliyuncs.com/xiaoduoai/devops-network-debug-tools:0.6
      imagePullPolicy: IfNotPresent
      name: network-debug-tools
      ports:
      - containerPort: 9091
        name: tcp
        protocol: TCP
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 100Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-dxzcg
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    imagePullSecrets:
    - name: zjk-vpc-aliyuncs
    nodeName: cd-033112-dev-tb-kubelet-all
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 420
        name: conf-query-panel
      name: config-volume
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-volume-claim
    - name: default-token-dxzcg
      secret:
        defaultMode: 420
        secretName: default-token-dxzcg
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-05-19T03:22:47Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-05-20T06:35:57Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-05-20T06:35:57Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-05-19T03:22:47Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://e7b2a792281cdf3d66869504c541110d38a6134bf1090ccd769c5bd13890c9f9
      image: registry.cn-zhangjiakou.aliyuncs.com/xiaoduoai/devops-network-debug-tools:0.5
      imageID: docker-pullable://registry.cn-zhangjiakou.aliyuncs.com/xiaoduoai/devops-network-debug-tools@sha256:b9f721336bbd9c8721c03a6a938fd7d4ea98b3268e4a87a21f45f133d9a6fcc4
      lastState:
        terminated:
          containerID: docker://235c14349f2ab6b648451992a13b3272568df9c8ab86feefe93a7f742aaa13cb
          exitCode: 255
          finishedAt: "2023-05-20T06:33:42Z"
          reason: Error
          startedAt: "2023-05-19T03:22:56Z"
      name: network-debug-tools
      ready: true
      restartCount: 1
      state:
        running:
          startedAt: "2023-05-20T06:35:56Z"
    - containerID: docker://867518e2572c2f902961d4d3f392463d1347bf6918aca105de342ea8b945e6c0
      image: registry.cn-zhangjiakou.aliyuncs.com/xiaoduoai/bigdata-query-panel:feat-drill-display
      imageID: docker-pullable://registry.cn-zhangjiakou.aliyuncs.com/xiaoduoai/bigdata-query-panel@sha256:b0e36e23ea58836b44ec538d04c3c37735573d0f1472933d9e702b3c724bab71
      lastState:
        terminated:
          containerID: docker://e92f7e2c9dc281864abb01bb9d25b6c0d023e7d8c896aaa6da07c3f8ceb8d22e
          exitCode: 255
          finishedAt: "2023-05-20T06:33:43Z"
          reason: Error
          startedAt: "2023-05-19T03:22:55Z"
      name: query-panel
      ready: true
      restartCount: 1
      state:
        running:
          startedAt: "2023-05-20T06:35:56Z"
    hostIP: 10.248.33.112
    phase: Running
    podIP: 10.244.39.20
    qosClass: Burstable
    startTime: "2023-05-19T03:22:47Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
