#!/bin/bash
# 此脚本主要用于练习如何识别参数中的选项
# 本脚本支持的选项为 -i 时间间隔,-o 日志输出路径,-c --count
# 定义 usage 函数,应用于 -h 选项
echo
usage() {
    echo "
    usage: [-i <interval>] [-o <output dir>] [-c <count of records>] [-h]
    -i 指定日志记录生成时间间隔
    -o 指定日志文件输出路径
    -c 指定日志记录生成总数
    -h 输出此页面
    "
}

# 使用getopt解析选项,并使用set命令将当前脚本参数转换成格式化后的参数
args=$(getopt i:o:c:h $@)
echo "args=$args"
if (($? != 0)); then
    exit 1
else
    set -- $args
fi
# 定义参数默认值
# 默认日志输出路径为/tmp/logs
arg_output="/tmp/logs"
# 默认值时间间隔为0
arg_interval=0
# 默认日志记录生成总数为100
arg_count=100

# 获取格式化后的参数
while [ "$1" != "" ]; do
    case "$1" in
    "-i")
        arg_interval=$2
        shift
        ;;
    "-o")
        arg_output=$2
        shift
        ;;
    "-c")
        arg_count=$2
        shift
        ;;
    "-h")
        usage
        exit 0
        ;;
    "--")
        shift
        break
        ;;
    *)
        echo "Unknown option $1"
        usage
        exit 1
        ;;
    esac
    shift
done

# 输出各个参数对应值
echo "logs dir: $arg_output
interval: $arg_interval
count: $arg_count"
