#!/bin/bash
# 方括号使用练习

# 1. 用于整型数据计算
var1=100
var2=200
# 可以使用$+双方括号来表示整型运算
var3=$[ $var1+$var2+1 ]
# 也可以使用$+双括号来表示整型运算
var4=$(($var1 + $var2 + 1))
echo $var3
echo $var4

# 2. 数值比较
n1=20
n2=10
if [ $n1 -ge $n2 ]; then
    echo "n1 is greater than or euqal to n2"
else
    echo "n1 is less than n2"
fi

# 3. 字符串比较
user=root
if [ $(whoami)=$user ]; then
    echo "root is online"
else
    echo "root is offline"
fi

# 4. 文件比较
fileName=test3
if [ -e $fileName ]; then
    echo "$fileName  exists"
else
    echo "$fileName doesn't exists"
fi

