#!/bin/bash
# 使用rsync同步集群文件
# 1. 获取输入参数个数，如果没有参数则直接退出
pcount=$#
if ((pcount == 0)); then
    echo "No parameters!"
    exit 1
fi

# 2. 若有输入参数则获取文件名
# 获取第一个参数
p1=$1
# 获取文件名或文件夹名
fName=$(basename $p1)
echo fName=$fName
# 3. 获取上级目录到绝对路径
parentDir=$(
    # 以物理路径进入，避免使用了因使用了路径链接而存放到错误路径下
    # 获取父路径
    $(
        cd -P $(dirname $p1)
        pwd
    )
)
echo parentDir=$parentDir

# 4. 获取当前用户名称
user=$(whoami)

# 5. 遍历主机hadoop101~hadoop103，将制定路径传输
for ((host = 101; host <= 103; host++)); do
    echo "---------hadoop$host----------"
#    rsync -rvl $parentDir/$fName $user@hadoop$host:$parentDir
done
