CREATE DATABASE IF NOT EXISTS tmp ON CLUSTER cluster_3s_2r
ENGINE=Ordinary


CREATE DATABASE IF NOT EXISTS ft_ods ON CLUSTER cluster_3s_2r
ENGINE=Ordinary


CREATE DATABASE IF NOT EXISTS ods ON CLUSTER cluster_3s_2r
ENGINE=Ordinary


CREATE DATABASE IF NOT EXISTS dwd ON CLUSTER cluster_3s_2r
ENGINE=Ordinary