select `day`,
    `platform`,
    `platform_cn`,
    `shop_id`,
    `shop_name`,
    `raw_info`,
    `category`,
    `type`,
    `id`,
    `status`,
    `handler`,
    `priority`,
    `create_time`,
    `creator`,
    `description`,
    `finish_time`,
    `eval_status`,
    `score`,
    `custom_opinion`,
    `order_id`,
    `money`,
    `order_status`,
    `order_goods`,
    `custom_goods`,
    `delivery_id`,
    `paid_time`,
    `product_time`,
    `logistics_expire_limit`,
    `reason_full`,
    `reason_level_1`,
    `reason_level_2`,
    `reason_level_3`,
    `reason_level_4`,
    `compensate_cnt`,
    `unit_name`,
    `compensate_type`,
    `transfer_money`,
    `relative_pic`,
    `factory_code`,
    `is_delivery_paid`,
    `is_special`
from (
        select `day`,
            `platform`,
            `platform_cn`,
            `shop_id`,
            `shop_name`,
            `raw_info`,
            `category`,
            `type`,
            `id`,
            `status`,
            `handler`,
            `priority`,
            `create_time`,
            `creator`,
            `description`,
            `finish_time`,
            `eval_status`,
            `score`,
            `custom_opinion`,
            `order_id`,
            `money`,
            `order_status`,
            `order_goods`,
            `custom_goods`,
            `delivery_id`,
            `paid_time`,
            `product_time`,
            `logistics_expire_limit`,
            `reason_full`,
            `reason_level_1`,
            `reason_level_2`,
            `reason_level_3`,
            `reason_level_4`,
            `compensate_cnt`,
            `unit_name`,
            `compensate_type`,
            `transfer_money`,
            `relative_pic`,
            `factory_code`,
            `is_delivery_paid`,
            `is_special`,
            row_number() over (
                partition by id
                order by JSONExtractString(
                        JSONExtractString(raw_info, 'job_info'),
                        'update_at'
                    )
            ) as num1
        from sxx_ods.compensate_workorder_all
        where day = { ds_nodash }
    ) as t1
where num1 = 1