SELECT
    seller_nick,
    platform,
    count(DISTINCT snick) AS snick_uv,
    sum(tagged_dialog_cnt) AS tagged_dialog_cnt,
    sum(ai_tagged_dialog_cnt) AS ai_tagged_dialog_cnt,
    sum(custom_tagged_dialog_cnt) AS custom_tagged_dialog_cnt,
    sum(manual_tagged_dialog_cnt) AS manual_tagged_dialog_cnt,
    sum(subtract_score_dialog_cnt) AS subtract_score_dialog_cnt,
    sum(add_score_dialog_cnt) AS add_score_dialog_cnt,
    sum(subtract_score_sum) AS subtract_score_sum,
    sum(subtract_score_sum) AS subtract_score_sum,
    sum(add_score_sum) AS add_score_sum,
    sum(ai_subtract_score_sum) AS ai_subtract_score_sum,
    sum(ai_add_score_sum) AS ai_add_score_sum,
    sum(custom_subtract_score_sum) AS custom_subtract_score_sum,
    sum(custom_add_score_sum) AS custom_add_score_sum,
    sum(manual_subtract_score_sum) AS manual_subtract_score_sum,
    sum(manual_add_score_sum) AS manual_add_score_sum,
    sum(dialog_cnt) AS dialog_cnt,
    sum(manual_marked_dialog_cnt) AS manual_marked_dialog_cnt,
    sum(ai_subtract_score_dialog_cnt) AS ai_subtract_score_dialog_cnt,
    sum(ai_add_score_dialog_cnt) AS ai_add_score_dialog_cnt,
    sum(custom_subtract_score_dialog_cnt) AS custom_subtract_score_dialog_cnt,
    sum(custom_add_score_dialog_cnt) AS custom_add_score_dialog_cnt,
    sum(manual_subtract_score_dialog_cnt) AS manual_subtract_score_dialog_cnt,
    sum(manual_add_score_dialog_cnt) AS manual_add_score_dialog_cnt
FROM xqc_dws.xplat_snick_stat_all
WHERE day = 20221001
GROUP BY seller_nick, platform